name: Build and Push Docker Images to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag Docker images
      run: |
        docker build -t w453y/wec-task-containerization:latest .
        docker tag w453y/wec-task-containerization:latest w453y/wec-task-containerization:latest

    - name: Push Docker images
      run: |
        docker push w453y/wec-task-containerization:latest
